---
title: "Homework_8_Wu_Inessa"
author: "Inessa Wu"
date: "March 20, 2018"
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, warning=FALSE, message=FALSE}
library (tidyverse)
library (rmarkdown)
library (mosaicData)
library (lubridate)
library(broom)
library(rpart)
library(partykit)
library(ROCR)
```

###Exercise 1

Titanic file contains 891 observations and 12 variables (columns)

```{r message=FALSE}

#Import titanic file
file_path <- 'C:/Users/ipodvorna/Documents/compscix-415-2-assignments/compscix-415-2-assignments/titanic.csv'
titanic_data <- read_delim(file = file_path, delim = ",")

glimpse(titanic_data)
```

###Exercise #2

Splitting data into training and test data sets (70/30)

```{r}
# Setting a seed to guarantee that the same random sample is
# generated every time, so long as the same seed is set beforehand

set.seed(29283)

# Creating training data set - 70% of data
titanic_train_set <- titanic_data %>% sample_frac(.7)

# Assigning the remaining 30% of data to testing data set
titanic_test_set <- titanic_data %>% filter(!(PassengerId %in% titanic_train_set$PassengerId))
```

###Exercise 3


# Fit a model with intercept only
mod_1 <- glm(_______ ~ _____, data = _____, family = 'binomial')

# take a look at the features and coefficients
tidy(____)


